import { UserButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button, Flex, Heading } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ozzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex p="4px">
          <UserButton afterSignOutUrl="/" />
        </Flex>

        <Flex alignItems="center" flexDir="column" width="100vw" height="100vh">
          <Heading pt="20vh" size="4xl">
            Ozzy
          </Heading>
          <Flex justifyContent="space-between" pt="10vh" width="15vw">
            <Link href="/sign-up">
              <Button>Sign Up</Button>
            </Link>
            <Link href="/sign-in">
              <Button>Sign In</Button>
            </Link>
          </Flex>
        </Flex>
      </main>
    </>
  );
};

export default Home;
