import { Box, Button, Center, Flex, Grid, Heading, Input, VStack, Text, HStack } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Lotty from "~/components/Lotty";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ozzy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center h="100vh" bg="##F6FEFD">
          <Lotty
            bottom="120px"
            right="70px"
            position="absolute"
            transform="scale(0.3)"
          />
        <Box
          w={["90%", "30%"]}
          bg="#FFFCF5"
          shadow="xl"
          rounded="xl"
        >
          <VStack paddingY={"3vh"} spacing={10}>
            <Heading size="3xl">Ozzy</Heading>
            <HStack
              spacing={5}
            >
            <Link href="/sign-in">
              <Button bg="#F79009" shadow="xl">
                Sign in
              </Button>
            </Link>
            <Link href="/sign-up">
              <Button bg="#F79009" shadow="xl">
                Sign Up
              </Button>
            </Link>
            
          </HStack>
          </VStack>
          
        </Box>
      </Center>
    </main>
    </>
  );
};
export default Home;
