name: CI

on: [push, pull-request]

env:
  DATABASE_URL: "https://dummyURL"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck

      - name: Lint
        run: npm run lint
